### ISSUE TITLE
RHEL 9 Yumrepo/RPMs

### ISSUE THREAD

**Issue by sohooo** [fullstaq-ruby/server-edition#106]
Hi,

the [README](https://github.com/fullstaq-ruby/server-edition#rhelcentos) shows yumrepos for the supported RHEL/CentOS versions 7 and 8, which we happily use :+1: 

As we're in the process of migrating to RHEL9, we'd like to know when (if?) there will be builds for that OS version.

Thanks!

**Comment by FooBarWidget** [comment]
The simple answer is that there will be builds as soon as one of these two things happen:

 1. I have free time to do it, -OR-
 2. Someone sends a pull request.

However, a prerequisite for this is that [Rocky Linux 9](https://forums.rockylinux.org/t/rhel-9-releasing-very-soon-rocky-9-beta/5932) needs to be released first, as well as a corresponding Docker image, because we'll be using that to build EL9-compatible RPMs.

**Comment by sohooo** [comment]
Ah I see, and thanks for the link to the Rocky Linux 9 forum thread.

**Comment by FooBarWidget** [comment]
Rocky Linux 9 has been released. But considering Hacker News comments, we may want to prefer Alma Linux going forward.
https://news.ycombinator.com/item?id=32100338
https://news.ycombinator.com/item?id=32100579

**Comment by FooBarWidget** [comment]
EL9 support is now released.
